service: aws-node-http-api-project
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  # runtime: nodejs14.x
  runtime: python3.8
  timeout: 30

functions:
  MyAuthFunction:
    description: Extracts api key, authenticates against usage plan, allow/deny http methods and returns auth response object
    handler: ./auth_function/app.lambda_handler

  BackendFunction:
    handler: ./short_funnel/app.lambda_handler
    events:
      - httpApi:
          method: get
          path: /shortfunnel-health/
          authorizer: MyAuthFunction
      - httpApi:
          method: post
          path: /shortfunnel-energy
          authorizer: MyAuthFunction

resources:
  Resources:
    ShortFunnelApi:
      DependsOn: MyAuthFunction
      Type: AWS::Serverless::Api
      Properties:
        StageName: dev
        EndpointConfiguration:
          Type: REGIONAL
        Auth:
            DefaultAuthorizer: MyLambdaRequestAuthorizer
            ApiKeyRequired: true
            Authorizers:
              MyLambdaRequestAuthorizer:
                FunctionPayloadType: REQUEST
                FunctionArn: !GetAtt MyAuthFunction.Arn
                Identity:
                  ReauthorizeEvery: 300
                  QueryStrings:
                    - apiKey

    ApiKey:
      Type: AWS::ApiGateway::ApiKey
      DependsOn: ShortFunnelApidevStage
      Properties:
        Name: !Join ["", [{"Ref": "AWS::StackName"}, "-apikey"]]
        Enabled: true
        StageKeys:
          - RestApiId: !Ref ShortFunnelApi
            StageName: dev
        Value: !Join ["", [{"Ref": "AWS::StackName"}, "-unbounce-key"]]

    UsagePlan:
      DependsOn: ShortFunnelApidevStage
      Type: AWS::ApiGateway::UsagePlan
      Properties:
        ApiStages:
          - ApiId: !Ref ShortFunnelApi
            Stage: dev
        Throttle:
          BurstLimit: 50
          RateLimit: 100
        UsagePlanName: MyUsagePlan

    UsagePlanKey:
      Type: AWS::ApiGateway::UsagePlanKey
      Properties:
        KeyId: !Ref ApiKey
        KeyType: API_KEY
        UsagePlanId: !Ref UsagePlan


  Outputs:
    ShortFunnelApiHealth:
      Description: "API Gateway endpoint URL for dev stage for api key validation in query string"
      Value: !Sub "https://${ShortFunnelApi}.execute-api.${AWS::Region}.amazonaws.com/dev/shortfunnel-health?apiKey=${AWS::StackName}-unbounce-key"
    ShortFunnelApiEnergy:
      Description: "API Gateway endpoint URL for dev stage for api key validation in query string"
      Value: !Sub "https://${ShortFunnelApi}.execute-api.${AWS::Region}.amazonaws.com/dev/shortfunnel-energy?apiKey=${AWS::StackName}-unbounce-key"
