version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "api-key-in-query-string-v3"
s3_prefix = "api-key-in-query-string-v3"
region = "ap-southeast-2"
confirm_changeset = false
disable_rollback = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_bucket = "unbounce-s3-bucket"

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "api-key-in-query-string-v3"
s3_prefix = "api-key-in-query-string-v3"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_bucket = "unbounce-s3-bucket"
